application: craigomation
version: alpha-001
runtime: go
api_version: go1

handlers:
- url: /(scripts|styles)/(.*)
  static_files: \1/\2
  upload: (scripts|styles)/.*

- url: /buy_request
  script: _go_app

- url: /request/(.*)
  script: _go_app

- url: /accept_request/(.*)
  script: _go_app

- url: /delivery_status/(.*)
  script: _go_app

- url: /get_cl
  script: _go_app

- url: /status/(.*)
  static_files: status.html
  upload: status.html

- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /.*
  static_files: index.html
  upload: index.html

skip_files:
- ^(.*/)?\.DS_Store$
