application: powerplug
version: alpha-001
runtime: go
api_version: go1

handlers:
- url: /(scripts|styles)/(.*)
  static_files: \1/\2
  upload: (scripts|styles)/.*

- url: /go_route
  script: _go_app

- url: /.*
  static_files: index.html
  upload: index.html

skip_files:
- ^(.*/)?\.DS_Store$